version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fact-checking-frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fact-checking-backend
    ports:
      - "8000:8000"
    restart: always
    # Entferne das Volume-Mapping, das die Dateien überschreibt
    # volumes:
    #   - ./backend:/app 